## Create HTML iframe object with local HTML document
## that displays the help manual
## (sourced .html file is generated by knitting help_page.Rmd)
tags$iframe(src="help_page.html",
            width="100%",
            height=550, ## FIXME: make height scale with browser window size
            frameborder=0,
            seamless="seamless" ## this doesn't actually seem to work... probably delete this
            )
