## Create HTML iframe object with local HTML document
## that displays the help manual
## (sourced .html file is generated by knitting help_page.Rmd)
# tags$div(style="position:relative;height=0;overflow:hidden;",
#          tags$iframe(src="help_page.html",
#               width="100%",
#               # height="100%",
#               # height=500, ## FIXME: make height scale with browser window size
#               frameborder=0,
#               seamless="seamless" ## this doesn't actually seem to work... probably delete this
#               )
#          )

tags$iframe(src="help_page.html",
            style="height: 100%; width: 100%; top: 0; left: 0; position: absolute; padding-top: 50px;",
            frameborder=0,
            seamless="seamless" ## this doesn't actually seem to work... probably delete this
         )



