---
title: "`rddapp` documentation style guide"
author: "Irena Papst"
output:
  pdf_document:
    latex_engine: xelatex
linkcolor: magenta
urlcolor: magenta
mainfont: Helvetica Neue
header-includes:
- \usepackage[fontsize=13pt]{scrextend}
---

Some notes to keep the writing and formatting style consistent within the docs for `rddapp`, including the `shiny` help page and the `rddapp` vignette.

# Headers
* Header levels are as follows:
    + 1: Page (e.g. Model, Power) or major tabs (e.g. Data, Estimates, etc. on Model page)
    + 2: Panels within pages
    + 3: Anything within tabs/panels
* Header anchors should be all lower case, with spaces replaced with underscores:
    + `## Data tab {#data_tab}`
* Headers should be in Sentence case.

# Text formatting

* Bold terms that are direct references to objects in the app interface (e.g. the **Data** panel, not the **Data panel**). Only bold the keyword (e.g. Data, Browse, gear), not the descriptor (e.g. panel, button, menu). Do not bold keywords in headers.
     * Discretionary bolding of other **keywords** is also helpful.
* Any software (`R`, `rddapp`) or code (`function()`) should be formatted as an inline code snipet (enclosed in \` marks).
* Use [embedded links](https://www.warnerbros.com/archive/spacejam/movie/jam.html) where possible (instead of plaintext urls).
