# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]


jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Install XQuartz
      run: |
        if [ ! -d "/opt/X11" ]; then
          echo "Installing XQuartz..."
          curl -OL https://dl.bintray.com/xquartz/downloads/XQuartz-2.8.1.dmg
          sudo hdiutil attach XQuartz-2.8.1.dmg
          sudo installer -pkg /Volumes/XQuartz-2.8.1/XQuartz.pkg -target /
          sudo hdiutil detach /Volumes/XQuartz-2.8.1
          echo "XQuartz installed."
        fi

    - name: Install tcltk package
      run: |
        sudo apt-get update
        sudo apt-get install -y tcl-dev tk-dev
        Rscript -e "install.packages('tcltk', dependencies = TRUE)"


name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
